'use strict'; const A=require('./_assert.js'); const M=require('../sidecar/authorized-auditor-measurement.js');
const input={planDigest:M.PLAN_DIGEST,provider:'ollama',maximumCostUsd:0,retries:0,recurrence:false,roleId:M.PLAN.roleId,championConfigurationId:M.PLAN.champion.configurationId,challengerConfigurationId:M.PLAN.challenger.configurationId};
(async()=>{ A.eq(M.validateStart(input),true,'exact authorized plan accepted'); for(const patch of [{planDigest:'x'},{provider:'openai'},{maximumCostUsd:.01},{retries:1},{recurrence:true},{roleId:'other'},{challengerConfigurationId:'other'}]){let refused=false;try{M.validateStart(Object.assign({},input,patch));}catch(_){refused=true;}A.ok(refused,'plan expansion refused');}
 const sealed=M.sealedRunOptions(M.PLAN.challenger); A.eq(sealed.provider,'ollama','sealed run is Ollama only'); A.eq(sealed.fallbackModels.length+sealed.fallbackProviders.length+sealed.keyPool.length,0,'sealed run disables all fallback and key rotation'); A.ok(sealed.isTask===false&&sealed.reflect===false,'sealed run exposes no tools or auxiliary model work'); A.eq(typeof sealed.emit,'function','sealed run has an inert event sink');
 A.eq(M.PLAN.predecessorPlanId,'auditor-matched-local-v1','replacement links the consumed plan'); let claimed=false,writes=0,syncs=0,closed=0; const fakeFs={openSync:()=>{if(claimed)throw new Error('EEXIST');claimed=true;return 7;},writeFileSync:()=>writes++,fsyncSync:()=>syncs++,closeSync:()=>closed++}; M.claimAttempt(fakeFs,'receipt',{}); let duplicate=false;try{M.claimAttempt(fakeFs,'receipt',{});}catch(_){duplicate=true;}A.ok(duplicate&&writes===1&&syncs===1&&closed===1,'attempt receipt is fsynced and one-shot');
 A.ok(M.receiptProvenance().sourceRefs.includes('change:PS-2026-066'),'replacement receipt retains failed-attempt provenance');
 const pre=await M.preflight({halted:()=>false,rosterChanged:()=>false,snapshot:async()=>({bytes:Buffer.from('[]'),hash:M.sha(Buffer.from('[]'))})},input);A.ok(pre.modelRuns===0&&pre.measurements===0&&pre.tasks===3,'preflight validates integration without inference or evidence');
 const bytes=Buffer.from('[]'), calls=[], settled=[]; const deps={halted:()=>false,rosterChanged:()=>false,snapshot:async t=>({bytes,hash:M.sha(bytes),path:t.file}),run:async x=>{calls.push(x);return {runId:'r'+calls.length,modelText:JSON.stringify(M.expected(x.task.id,bytes)),costUsd:0};},settle:async x=>{settled.push(x);return x;}}; const out=await M.execute(deps,input); A.eq(out.runs.length,6,'exactly six runs'); A.eq(calls.filter(x=>x.arm==='challenger').length,3,'inactive challenger runs only in isolated callback'); A.ok(calls.every(x=>x.provider==='ollama'),'Ollama only'); A.ok(settled.every(x=>x.agreement),'mechanical verification required'); A.eq(new Set(calls.map(x=>x.task.id+':'+x.snapshot.hash+':'+x.instructionHash)).size,3,'paired inputs and instructions identical');
 let halted=false;try{await M.execute(Object.assign({},deps,{halted:()=>true}),input);}catch(_){halted=true;}A.ok(halted,'E-stop fails closed'); A.report('authorized-auditor-measurement.test');})().catch(e=>{console.error(e);process.exitCode=1;});
