'use strict';
const A = require('./_assert.js'); const { appendSharedReport } = require('../sidecar/memory-store.js'); const { evaluateConfigurations } = require('../sidecar/champion-challenger.js');
let reports; const store = { get: () => reports, update: async (k, fn) => { const n = await fn(reports); if (n !== undefined) reports = n; return n; } };
const objectives = [
  { id: 'c1', status: 'completed', assignedRoleId: 'research.general_researcher', admittedRunId: 'r1', completionEvidenceRefs: ['report:c1'] },
  { id: 'c2', status: 'failed', assignedRoleId: 'research.general_researcher', admittedRunId: 'r2', completionEvidenceRefs: [] },
  { id: 'n1', status: 'completed', assignedRoleId: 'research.general_researcher', admittedRunId: 'r3', completionEvidenceRefs: ['report:n1'] },
  { id: 'n2', status: 'completed', assignedRoleId: 'research.general_researcher', admittedRunId: 'r4', completionEvidenceRefs: ['report:n2'] }
];
const runs = [{ runId: 'r1', usd: .2 }, { runId: 'r2', usd: .2 }, { runId: 'r3', usd: .1 }, { runId: 'r4', usd: .1 }];
const digest = 'a'.repeat(64), measurement = (arm, configurationId, objectiveId, runId, taskId) => ({ schema: 'pine-star.matched-measurement.v1', measurementId: arm + '-' + taskId, cohortId: 'research-v2', arm, roleId: 'research.general_researcher', configurationId, taskId, conditionsDigest: digest, objectiveId, runId, sourceRefs: ['objective:' + objectiveId, 'run:' + runId] });
const measurements = [measurement('champion', 'research-v1', 'c1', 'r1', 'task-1'), measurement('champion', 'research-v1', 'c2', 'r2', 'task-2'), measurement('challenger', 'research-v2', 'n1', 'r3', 'task-1'), measurement('challenger', 'research-v2', 'n2', 'r4', 'task-2')];
const deps = { objectives, runs, measurements, appendReport: r => appendSharedReport(store, r), getReport: id => (reports || []).find(x => x.id === id) || null, now: () => 500 };
(async () => {
  const spec = { evaluationId: 'research-v2', champion: { configurationId: 'research-v1', objectiveIds: ['c1', 'c2'] }, challenger: { configurationId: 'research-v2', objectiveIds: ['n1', 'n2'] } };
  const out = await evaluateConfigurations(deps, spec); A.eq(out.verdict, 'challenger_recommended', 'strict no-worse complete evidence can recommend challenger'); A.eq(out.evidenceComplete, true, 'matched runs, adequate cohorts, and completion evidence pass the evidence gate'); A.eq(out.configurationChanged, false, 'evaluation cannot change configuration'); A.eq(out.activationPerformed, false, 'evaluation cannot activate configuration'); A.eq(out.spendingAuthorityUsd, 0, 'evaluation grants zero spend'); A.ok(out.report.sourceRefs.includes('run:r4') && out.report.sourceRefs.includes('evaluation-evidence:complete-v1'), 'report retains run provenance and complete-evidence marker');
  A.eq((await evaluateConfigurations(deps, spec)).idempotent, true, 'stable retry is idempotent');
  let conflict = false; try { await evaluateConfigurations(deps, Object.assign({}, spec, { challenger: { configurationId: 'research-v3', objectiveIds: ['n1', 'n2'] } })); } catch (e) { conflict = /differently/.test(e.message); } A.ok(conflict, 'stable identity rejects changed cohort');
  let overlap = false; try { await evaluateConfigurations(deps, { evaluationId: 'overlap', champion: { configurationId: 'a', objectiveIds: ['c1'] }, challenger: { configurationId: 'b', objectiveIds: ['c1'] } }); } catch (e) { overlap = /share/.test(e.message); } A.ok(overlap, 'cohorts cannot share objectives');
  let active = false; try { await evaluateConfigurations(Object.assign({}, deps, { objectives: objectives.concat({ id: 'active', status: 'assigned', assignedRoleId: 'research.general_researcher' }) }), { evaluationId: 'active', champion: { configurationId: 'a', objectiveIds: ['active'] }, challenger: { configurationId: 'b', objectiveIds: ['n1'] } }); } catch (e) { active = /settled/.test(e.message); } A.ok(active, 'only settled evidence is evaluated');
  const uncertain = await evaluateConfigurations(Object.assign({}, deps, { runs: runs.map(r => r.runId === 'r3' ? Object.assign({}, r, { uncertainMutations: [{ callId: 'x' }] }) : r) }), Object.assign({}, spec, { evaluationId: 'uncertain' })); A.eq(uncertain.verdict, 'inconclusive', 'uncertain mutations prevent a promotion recommendation'); A.ok(uncertain.report.evaluationLessons.some(x => x.kind === 'uncertain_mutation' && x.arm === 'challenger'), 'uncertain mutation becomes an immutable experiment-design lesson');
  const missingRun = await evaluateConfigurations(Object.assign({}, deps, { runs: runs.filter(r => r.runId !== 'r4') }), Object.assign({}, spec, { evaluationId: 'missing-run' })); A.eq(missingRun.verdict, 'inconclusive', 'missing measured run evidence prevents recommendation'); A.ok(missingRun.report.evaluationLessons.some(x => x.kind === 'missing_run_measurement' && x.configurationId === 'research-v2'), 'missing run measurement becomes a structured lesson');
  const unrelated = await evaluateConfigurations(Object.assign({}, deps, { measurements: measurements.map(x => x.objectiveId === 'n2' ? Object.assign({}, x, { taskId: 'unrelated-history' }) : x) }), Object.assign({}, spec, { evaluationId: 'unrelated-history' })); A.eq(unrelated.evidenceComplete, false, 'unrelated historical objectives cannot be called matched'); A.ok(!unrelated.report.sourceRefs.includes('evaluation-evidence:complete-v1'), 'mismatched tasks cannot earn the complete evidence marker');
  const weak = await evaluateConfigurations(deps, { evaluationId: 'weak', champion: { configurationId: 'a', objectiveIds: ['c1'] }, challenger: { configurationId: 'b', objectiveIds: ['n1'] } }); A.eq(weak.verdict, 'inconclusive', 'one-item cohorts remain too weak to recommend'); A.eq(weak.report.evaluationLessons.filter(x => x.kind === 'small_cohort').length, 2, 'small cohorts retain one structured lesson per arm');
  const missingEvidence = await evaluateConfigurations(Object.assign({}, deps, { objectives: objectives.map(x => x.id === 'n2' ? Object.assign({}, x, { completionEvidenceRefs: [] }) : x) }), Object.assign({}, spec, { evaluationId: 'missing-evidence' })); A.ok(missingEvidence.report.evaluationLessons.some(x => x.kind === 'missing_completion_evidence' && x.arm === 'challenger'), 'missing completion evidence becomes a structured lesson');
  const unlabeled = await evaluateConfigurations(Object.assign({}, deps, { measurements: [] }), Object.assign({}, spec, { evaluationId: 'unlabeled' })); A.eq(unlabeled.verdict, 'inconclusive', 'caller-supplied configuration labels cannot substitute for authoritative measurements'); A.eq(unlabeled.configurationChanged, false, 'incomplete evidence remains advisory only');
  A.report('champion-challenger.test');
})().catch(e => { console.error(e); process.exitCode = 1; });
