'use strict';
const A = require('./_assert.js');
const { makeProductProjectStore } = require('../sidecar/product-project-store.js');
const fs = require('fs'), path = require('path'), os = require('os');
let rows, stamp = 100;
const durable = { get: () => rows, readKey: () => ({ status: rows ? 'ok' : 'absent', value: rows }), update: async (key, fn) => { const next = await fn(rows); if (next !== undefined) rows = next; return next; } };
const objectives = new Map([['objective:research', { id: 'objective:research', status: 'completed', assignedRoleId: 'research.general_researcher' }]]);
const reports = new Map([['report:research', { id: 'report:research', type: 'research', createdAt: 90 }]]);
const store = makeProductProjectStore({ durable, now: () => stamp++, newId: () => 'generated', objectiveExists: id => objectives.get(id), reportExists: id => reports.get(id) });
(async () => {
  const made = await store.create({ projectId: 'Trail Planner', title: 'Pine Trail Planner', targetMarketplaces: ['Etsy', 'Shopify'], estimatedCostUsd: 'unknown', credentials: 'secret', publishAutomatically: true });
  A.eq(made.project.id, 'trail-planner', 'stable project ID is normalized');
  A.eq(made.project.status, 'idea', 'new product starts as an idea');
  A.eq(made.project.spendingAuthorityUsd, 0, 'business records carry zero spending authority');
  A.eq(made.project.estimatedCostUsd, null, 'unknown cost remains unknown');
  A.eq(made.project.revenueUsd, null, 'unknown revenue remains unknown');
  A.eq(made.project.credentials, undefined, 'unknown/credential fields are not persisted');
  A.eq((await store.create({ projectId: 'Trail Planner', title: 'Pine Trail Planner' })).idempotent, true, 'same stable identity and scope is idempotent');
  let conflict = false; try { await store.create({ projectId: 'Trail Planner', title: 'Another product' }); } catch (e) { conflict = /another/.test(e.message); } A.ok(conflict, 'stable identity cannot be silently reused');
  const research = await store.update('trail-planner', { status: 'research', revision: 1, nextAction: 'Validate demand' });
  A.eq(research.status, 'research', 'valid forward transition persists');
  let skipped = false; try { await store.update('trail-planner', { status: 'production' }); } catch (e) { skipped = /transition/.test(e.message); } A.ok(skipped, 'workflow stages cannot be silently skipped');
  await store.update('trail-planner', { status: 'planned' }); await store.update('trail-planner', { status: 'production' }); await store.update('trail-planner', { status: 'qa' });
  let qaBlocked = false; try { await store.update('trail-planner', { status: 'listing_ready' }); } catch (e) { qaBlocked = /passed QA/.test(e.message); } A.ok(qaBlocked, 'listing readiness requires QA evidence');
  await store.update('trail-planner', { qaState: 'passed' }); await store.update('trail-planner', { status: 'listing_ready' }); await store.update('trail-planner', { status: 'approval_required' });
  let publicationBlocked = false; try { await store.update('trail-planner', { status: 'published' }); } catch (e) { publicationBlocked = /protected approval/.test(e.message); } A.ok(publicationBlocked, 'safe update path cannot publish externally');
  const linked = await store.link('trail-planner', { objectiveIds: ['objective:research'], reportIds: ['report:research'] });
  A.eq(linked.linkedObjectiveIds, ['objective:research'], 'durable objective link is stored');
  A.eq(linked.linkedReportIds, ['report:research'], 'durable report link is stored');
  A.eq((await store.link('trail-planner', { objectiveIds: ['objective:research'] })).revision, linked.revision, 'link retries are idempotent');
  let missing = false; try { await store.link('trail-planner', { objectiveIds: ['objective:missing'] }); } catch (e) { missing = /not found/.test(e.message); } A.ok(missing, 'fabricated work links are rejected');
  const progress = store.progress('trail-planner'); A.eq(progress.objectives[0].status, 'completed', 'linked objective progress remains inspectable'); A.eq(progress.reports[0].type, 'research', 'linked report evidence remains inspectable');
  A.eq(store.readStatus().status, 'ok', 'durable health is exposed');
  const workspaces = fs.mkdtempSync(path.join(os.tmpdir(), 'pine-product-projects-'));
  const diskDeps = { fs, path, workspaces, now: () => 500, newId: () => 'disk-id', objectiveExists: () => false, reportExists: () => false };
  await makeProductProjectStore(diskDeps).create({ projectId: 'restart-proof', title: 'Restart Proof' });
  A.eq(makeProductProjectStore(diskDeps).get('restart-proof').title, 'Restart Proof', 'product project survives store reconstruction from disk');
  A.report('product-project-store.test');
})().catch(e => { console.error(e); process.exitCode = 1; });
