'use strict';
const A = require('./_assert.js');
const Reports = require('../frontend/app/reports.js');
const html = Reports.reportHtml({ type: 'morning-brief', createdAt: 1, headline: '<b>done</b>', completed: ['made & checked'], exceptions: ['none <script>'], sourceRefs: ['/api/runs'] });
A.ok(html.includes('&lt;b&gt;done&lt;/b&gt;') && !html.includes('<b>done</b>'), 'report headline is escaped');
A.ok(html.includes('made &amp; checked') && html.includes('none &lt;script&gt;'), 'report sections are escaped');
A.ok(html.includes('COMPLETED') && html.includes('EXCEPTIONS') && html.includes('SOURCES'), 'readable report sections render when present');
const sparse = Reports.reportHtml({ headline: 'quiet day' });
A.ok(!sparse.includes('NEXT ACTIONS') && sparse.includes('quiet day'), 'empty sections are omitted without hiding the report');
const bundle = Reports.exportBundle([{ id: 'r1', headline: 'done' }], 123);
A.eq(bundle.schema, 'pine-star.shared-report-export.v1', 'local export has a versioned adapter contract');
A.eq(bundle.destination, null, 'export selects no external destination');
A.eq(bundle.externalWritePerformed, false, 'export truthfully records that no external write occurred');
const md = Reports.markdown([{ type: 'daily', createdAt: 1, headline: 'Day one', completed: ['built it'], exceptions: ['none'] }]);
A.ok(md.includes('# Pine Star shared reports') && md.includes('### Completed') && md.includes('- built it'), 'Markdown export is concise and human-readable');
A.ok(md.includes('no external vault was modified'), 'Markdown export states its local-only boundary');
A.ok(!Reports.markdown([{ headline: '<script>x</script>' }]).includes('<script>'), 'Markdown export escapes embedded HTML');
const scoutReport = Reports.reportHtml({ type: 'open-source-scout', headline: 'Scout', discoveries: [{ name: '<Tool>', source: 'Git&Hub', license: '', cost: '', compatibility: 'Windows', purpose: 'Useful<script>', relevance: 'Pine & Star', recommendation: 'WATCH', risk: '<unknown>', recommendedOwnerRoleId: 'development.integration_engineer' }] });
A.ok(scoutReport.includes('DISCOVERIES') && scoutReport.includes('&lt;Tool&gt;') && scoutReport.includes('Git&amp;Hub'), 'Scout discoveries render in the existing report surface with escaping');
A.ok(!scoutReport.includes('<script>') && scoutReport.includes('development.integration_engineer'), 'Scout purpose, risk, and owner fields render safely');
const objective = Reports.objectiveHtml({ title: '<img src=x>', status: 'approval_required', assignedRoleId: 'operations.coordinator', maxModelTier: 'balanced', approvalState: 'required', requiredCapabilities: ['publish<script>'], routing: { reason: 'Commander <approval>' }, completionEvidenceRefs: ['report:1&2'] });
A.ok(objective.includes('&lt;img src=x&gt;') && !objective.includes('<img src=x>'), 'objective title is escaped');
A.ok(objective.includes('APPROVAL_REQUIRED') && objective.includes('APPROVAL · REQUIRED'), 'objective status and approval boundary are visible');
A.ok(objective.includes('publish&lt;script&gt;') && objective.includes('Commander &lt;approval&gt;') && objective.includes('report:1&amp;2'), 'objective capabilities, routing reason, and evidence are escaped');
const settledObjective = Reports.objectiveHtml({ title: 'done', status: 'completed', settlementReason: 'done<script>', resultSummary: 'bounded & useful' });
A.ok(settledObjective.includes('done&lt;script&gt;') && settledObjective.includes('bounded &amp; useful'), 'objective settlement summary renders safely');
const relatedObjective = Reports.objectiveHtml({ title: 'child', parentObjectiveId: 'objective:parent<script>', dependsOnObjectiveIds: ['objective:first&'], decomposition: { childIds: ['objective:child>'] } });
A.ok(relatedObjective.includes('PARENT') && relatedObjective.includes('objective:parent&lt;script&gt;'), 'parent objective relationship renders safely');
A.ok(relatedObjective.includes('DEPENDS ON') && relatedObjective.includes('objective:first&amp;') && relatedObjective.includes('CHILDREN') && relatedObjective.includes('objective:child&gt;'), 'dependency and child relationships render safely');
const auditObjective = Reports.objectiveHtml({ title: 'audit', auditTargetObjectiveId: 'objective:target<script>' });
A.ok(auditObjective.includes('AUDIT TARGET') && auditObjective.includes('objective:target&lt;script&gt;'), 'audit target relationship renders safely');
const role = Reports.roleHtml({ id: 'research.general', displayName: '<Researcher>', department: 'research', modelTier: 'economy', capabilities: ['verify&report'], availability: 'active' });
A.ok(role.includes('&lt;Researcher&gt;') && role.includes('research.general') && role.includes('verify&amp;report'), 'role identity and capabilities render safely');
const product = Reports.productProjectHtml({ project: { title: '<Planner>', status: 'approval_required', productType: 'printable&pdf', qaState: 'passed', listingState: 'ready', publicationState: 'approval_required', targetCustomer: '<hiker>', targetMarketplaces: ['Market&One'], blockers: ['Needs <review>'], evidenceRefs: ['report:qa&1'], nextAction: 'wait & review' }, progress: { objectives: [{ id: 'objective:<research>', status: 'completed' }] } });
A.ok(product.includes('&lt;Planner&gt;') && product.includes('APPROVAL_REQUIRED') && product.includes('PUBLICATION · APPROVAL_REQUIRED'), 'product project status and publication boundary render visibly');
A.ok(!product.includes('<hiker>') && product.includes('&lt;hiker&gt;') && product.includes('objective:&lt;research&gt; [completed]'), 'product project customer and linked progress are escaped');
A.ok(product.includes('LISTING · READY') && product.includes('Market&amp;One') && product.includes('Needs &lt;review&gt;') && product.includes('report:qa&amp;1'), 'listing, marketplace, blocker, and evidence readiness details render safely');
const portfolio = Reports.productPortfolioHtml([{ project: { id: 'a', status: 'listing_ready', qaState: 'passed', blockers: [] } }, { project: { id: 'b', status: 'production', qaState: 'failed', blockers: ['fix'] } }], [{ id: 'c1', projectId: 'a', state: 'observed_published' }], { byProject: [{ projectId: 'a', netUsd: 6.25, entryCount: 2 }, { projectId: '<unknown>', netUsd: 500, entryCount: 1 }] });
A.ok(portfolio.includes('2 PRODUCTS') && portfolio.includes('LISTING_READY 1') && portfolio.includes('PRODUCTION 1'), 'portfolio summary renders deterministic stage counts');
A.ok(portfolio.includes('FAILED QA · 1') && portfolio.includes('BLOCKED · 1') && portfolio.includes('OBSERVED PUBLICATION · 1'), 'portfolio summary renders readiness attention without controls');
A.ok(!/<button|onclick=|<form/i.test(portfolio), 'portfolio summary exposes no action control');
A.ok(portfolio.includes('RECORDED PRODUCT CONTRIBUTION') && portfolio.includes('$6.25') && portfolio.includes('2 EVIDENCED ENTRIES'), 'portfolio shows only linked recorded product contribution');
A.ok(!portfolio.includes('&lt;unknown&gt;') && portfolio.includes('missing costs are not estimated'), 'unknown products are excluded and missing-cost boundary is explicit');
const commerce = Reports.commerceRecordHtml({ projectId: '<project>', marketplace: 'Market&One', state: 'observed_published', externalListingId: '<listing>', listingUrl: 'https://example.invalid/?a=1&b=2', evidenceRefs: ['file:export<script>'] });
A.ok(commerce.includes('&lt;project&gt;') && commerce.includes('Market&amp;One') && commerce.includes('&lt;listing&gt;') && commerce.includes('&amp;b=2'), 'commerce observations render escaped references');
A.ok(!commerce.includes('<script>') && commerce.includes('no marketplace action performed'), 'commerce evidence is escaped and boundary is explicit');
const ledger = Reports.businessLedgerHtml({ summary: { revenueUsd: 14.5, expenseUsd: 2.5, refundUsd: 1, netUsd: 11, entryCount: 3 }, entries: [{ type: 'revenue', amountUsd: 14.5, currency: 'USD', occurredAt: 1, source: '<export>', projectId: 'planner&one', evidenceRefs: ['row:<1>'] }] });
A.ok(ledger.includes('NET $11.00') && ledger.includes('REVENUE $14.50') && ledger.includes('EXPENSES $2.50') && ledger.includes('REFUNDS $1.00'), 'business ledger renders truthful recorded totals');
A.ok(ledger.includes('&lt;export&gt;') && ledger.includes('planner&amp;one') && ledger.includes('row:&lt;1&gt;'), 'business entry source, project, and evidence are escaped');
A.ok(!/<button|onclick=|<form|href=/i.test(commerce + ledger), 'commerce and ledger inspection expose no action or external navigation control');
const businessExport = Reports.businessExportBundle([{ project: { id: 'p1', title: 'Planner', status: 'listing_ready', credentials: 'must-drop', blockers: ['none'] } }], [{ id: 'c1', projectId: 'p1', marketplace: 'Market', state: 'draft', apiKey: 'must-drop' }], { summary: { entryCount: 1, revenueUsd: 4, netUsd: 4 }, entries: [{ id: 'e1', type: 'revenue', amountUsd: 4, source: 'export', evidenceRefs: ['row:1'], secret: 'must-drop', occurredAt: 2 }] }, 123);
A.eq(businessExport.schema, 'pine-star.business-snapshot-export.v1', 'business export has a versioned bounded contract');
A.eq(businessExport.destination, null, 'business export selects no external destination');
A.eq(businessExport.externalWritePerformed, false, 'business export records that no external write occurred');
A.ok(JSON.stringify(businessExport).indexOf('must-drop') < 0, 'business export allowlist drops unknown credential/private fields');
A.eq(businessExport.products[0].status, 'listing_ready', 'business export retains bounded product readiness');
A.eq(businessExport.ledger[0].amountUsd, 4, 'business export retains evidenced financial amount');
A.report('reports-ui.test');
