'use strict';
function text(v, n) { return String(v == null ? '' : v).trim().slice(0, n); }
function list(v, cap, n) { return [...new Set((Array.isArray(v) ? v : []).map(x => text(x, n)).filter(Boolean))].slice(0, cap); }
function normalizeListing(v) { const row = v && typeof v === 'object' ? v : {}, title = text(row.title, 200), description = text(row.description, 2000); if (!title || !description) throw new Error('passed QA requires listing title and description'); return { title, description, tags: list(row.tags, 13, 80), seoKeywords: list(row.seoKeywords, 20, 100), targetMarketplaces: list(row.targetMarketplaces, 8, 100) }; }
function coverage(v) { if (!Array.isArray(v)) return []; return v.slice(0, 20).map(x => ({ deliverable: text(x && x.deliverable, 240), artifactId: text(x && x.artifactId, 120) })).filter(x => x.deliverable && x.artifactId); }
function normalizeQa(input) {
  const row = input && typeof input === 'object' ? input : {}, projectId = text(row.projectId, 100), qaObjectiveId = text(row.qaObjectiveId, 120), outcome = ['passed', 'failed'].includes(row.outcome) ? row.outcome : '';
  if (!projectId || !qaObjectiveId || !outcome) throw new Error('QA finalization requires project, QA objective, and passed/failed outcome');
  const deliverableEvidence = coverage(row.deliverableEvidence), artifactIds = list((Array.isArray(row.artifactIds) ? row.artifactIds : []).concat(deliverableEvidence.map(x => x.artifactId)), 20, 120), reportIds = list(row.reportIds, 20, 120); if (!artifactIds.length || !reportIds.length) throw new Error('QA finalization requires verified artifact and report evidence');
  if (outcome === 'passed' && !deliverableEvidence.length) throw new Error('passed QA requires explicit expected-deliverable coverage');
  return { projectId, qaObjectiveId, outcome, artifactIds, reportIds, deliverableEvidence, checks: list(row.checks, 20, 240), exceptions: list(row.exceptions, 12, 240), listingDraft: outcome === 'passed' ? normalizeListing(row.listingDraft) : null };
}
async function finalizeQa(deps, input) {
  const d = deps || {}, row = normalizeQa(input); if (!d.projects || !d.objectives || typeof d.artifactExists !== 'function' || typeof d.reportExists !== 'function' || typeof d.appendReport !== 'function' || typeof d.getReport !== 'function') throw new Error('QA workflow requires project, objective, artifact, and report stores');
  const project = d.projects.get(row.projectId); if (!project) throw new Error('product project not found'); if (!['production', 'qa', 'listing_ready'].includes(project.status)) throw new Error('product project is not ready for QA finalization');
  if (row.outcome === 'passed') { const expected = list(project.deliverables, 20, 240), covered = new Set(row.deliverableEvidence.map(x => x.deliverable)); if (!expected.length || expected.some(name => !covered.has(name)) || row.deliverableEvidence.some(x => !expected.includes(x.deliverable))) throw new Error('passed QA must map every expected deliverable to verified artifact evidence'); }
  if (row.outcome === 'passed' && project.listingDraft && JSON.stringify(project.listingDraft) !== JSON.stringify(row.listingDraft)) throw new Error('QA listing draft already recorded differently');
  const objective = d.objectives.get(row.qaObjectiveId); if (!objective || !project.linkedObjectiveIds.includes(objective.id) || objective.assignedRoleId !== 'operations.quality_reviewer') throw new Error('QA objective is not the linked Quality Reviewer objective'); if (objective.status !== 'completed') throw new Error('QA objective is not completed');
  const missingArtifact = row.artifactIds.find(id => !d.artifactExists(id)), missingReport = row.reportIds.find(id => !d.reportExists(id)); if (missingArtifact) throw new Error('QA artifact evidence not found: ' + missingArtifact); if (missingReport) throw new Error('QA report evidence not found: ' + missingReport);
  const draft = { id: 'product-qa:' + project.id, type: 'product-qa', createdAt: typeof d.now === 'function' ? d.now() : Date.now(), headline: row.outcome.toUpperCase() + ' QA: ' + project.title, completed: row.checks, exceptions: row.exceptions, decisions: ['QA ' + row.outcome + '; publication is not authorized.'], nextActions: [row.outcome === 'passed' ? 'Review listing copy and request protected publication approval when ready.' : 'Correct QA exceptions and run a new reviewed QA objective.'], deliverableEvidence: row.deliverableEvidence, sourceRefs: ['product-project:' + project.id, 'objective:' + objective.id].concat(row.artifactIds.map(id => 'deliverable:' + id), row.reportIds.map(id => 'report:' + id)) };
  const prior = d.getReport(draft.id), sameReport = prior && ['type', 'headline', 'completed', 'exceptions', 'decisions', 'nextActions', 'sourceRefs', 'deliverableEvidence'].every(k => JSON.stringify(prior[k] || []) === JSON.stringify(draft[k] || [])); if (prior && !sameReport) throw new Error('QA outcome already recorded differently'); const saved = prior ? { added: false, report: prior } : await d.appendReport(draft);
  let current = await d.projects.link(project.id, { reportIds: [saved.report.id] });
  if (row.outcome === 'failed' && current.status !== 'listing_ready' && current.qaState !== 'failed') current = await d.projects.update(current.id, { qaState: 'failed', revision: current.revision, blockers: row.exceptions.length ? row.exceptions : ['QA failed without itemized exceptions'], nextAction: 'Correct QA exceptions before listing preparation', evidenceRefs: row.artifactIds.concat(row.reportIds) });
  if (row.outcome === 'passed' && current.status === 'production') current = await d.projects.update(current.id, { status: 'qa', qaState: 'passed', revision: current.revision, blockers: [], listingDraft: row.listingDraft, nextAction: 'Prepare internal listing copy and SEO metadata', evidenceRefs: row.artifactIds.concat(row.reportIds) });
  if (row.outcome === 'passed' && current.status === 'qa') current = await d.projects.update(current.id, { status: 'listing_ready', qaState: 'passed', revision: current.revision, listingDraft: row.listingDraft, nextAction: 'Review listing draft before requesting protected publication approval' });
  return { schema: 'pine-star.product-qa.v1', idempotent: !saved.added && project.status === current.status && project.revision === current.revision, outcome: row.outcome, project: current, report: saved.report, objective };
}
module.exports = { normalizeQa, finalizeQa };
